language: python

python:
    - "3.5"
    - "3.6"

install:
    - pip install docutils
    - pip install nose
    - pip install nose-exclude
    - pip install coverage
    - pip install coveralls
    - pip install pycodestyle
    - pip install .

script:
    - python setup.py nosetests
    - pycodestyle pysphinxdoc --ignore="E121,E123,E126,E226,E24,E704,E402,E731,W601,W504" --exclude="pysphinxdoc/sphinxext"

after_success:
    - coveralls
