language: python

python:
    - "2.7"
    - "3.4"

install:
    - pip install docutils
    - pip install coverage
    - pip install coveralls
    - pip install pep8
    - pip install .

script:
    - sphinxdoc -p . -n pysphinxdoc -o ./doc -v 2
    - pep8 . --ignore="E121,E123,E126,E226,E24,E704,E402,E731,W601"

after_success:
    - coveralls
